# Generated by Django 5.0.3 on 2024-03-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description1',
            field=models.CharField(default='blabla', max_length=100),
        ),
    ]
